DROP TABLE IF EXISTS restaurant;

CREATE TABLE restaurant (
                            id BIGINT PRIMARY KEY AUTO_INCREMENT,
                            record_number INT,
                            service_name VARCHAR(100),
                            service_id VARCHAR(50),
                            region_code VARCHAR(10),
                            management_number VARCHAR(50),
                            license_date DATE,
                            cancel_date DATE,
                            business_status_code VARCHAR(10),
                            business_status_name VARCHAR(20),
                            detail_status_code VARCHAR(10),
                            detail_status_name VARCHAR(20),
                            close_date DATE,
                            suspend_start_date DATE,
                            suspend_end_date DATE,
                            reopen_date DATE,
                            phone VARCHAR(50),
                            area_size VARCHAR(20),
                            postal_code VARCHAR(10),
                            full_address VARCHAR(255),
                            road_address VARCHAR(255),
                            road_postal_code VARCHAR(10),
                            store_name VARCHAR(255),
                            last_modified TIMESTAMP,
                            data_update_type VARCHAR(5),
                            data_update_date TIMESTAMP,
                            business_type VARCHAR(50),
                            coord_x DOUBLE,
                            coord_y DOUBLE,
                            sanitation_type VARCHAR(50),
                            male_employee INT,
                            female_employee INT,
                            around_info VARCHAR(50),
                            grade VARCHAR(20),
                            water_type VARCHAR(50),
                            total_employees INT,
                            hq_employees INT,
                            office_employees INT,
                            sales_employees INT,
                            production_employees INT,
                            building_ownership VARCHAR(50),
                            guarantee_amount BIGINT,
                            monthly_rent BIGINT,
                            multi_use_yn CHAR(1),
                            total_scale VARCHAR(50),
                            traditional_id VARCHAR(100),
                            main_menu VARCHAR(255),
                            homepage VARCHAR(255)
);
